sources:
  - ReadexPro.glyphs
familyName: "Readex Pro"
buildOTF: False
buildWebfont: False
axisOrder:
  - HEXP
  - wght
stat:
  - name: Hyper Expansion
    tag: HEXP
    values:
    - name: Default
      value: 0
      flags: 2
  - name: Weight
    tag: wght
    values:
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700